### ISSUE TITLE
Wrapping C/C++ for Python

### ISSUE THREAD

**Issue by licode** [scikit-beam/scikit-beam#110]
Description
====

C/C++ code will be integrated into the project to deal with the case of heavy computation. Proper wrappers need to be chosen in order to keep the current project scalable and integrated. 

Options
====
- [ ] Cython
- [ ] Ctypes
- [ ] SWIG
- [ ] SIP
- [ ] pyrex
- [ ] Boost.Python

**Comment by ericdill** [comment]
My vote is for Cython

**Comment by ericdill** [comment]
Any objections to standardizing on Cython?

**Comment by ericdill** [comment]
Cython it is!
