### ISSUE TITLE
Fitting strategy in fluorescence data analysis

### ISSUE THREAD

**Issue by licode** [scikit-beam/scikit-beam#122]
Description
====

Fitting strategy suggested by @Tillsten  from https://github.com/lmfit/lmfit-py/issues/107

> OT fitting fluorescence: While the Gaussian is the most commonly used line-shape for fitting fluorescence spectra, it is the wrong model in a lot cases, e.g. red edge effect. For fitting complicated spectra which are a sum of components - f(x, \psi) = \sum_i c_i * f(x, \psi) - it can be helpful to only fit the non-linear parameters with levenberg. With them you build a normalized basis a than solve the linear least sqaures problem to calculate the coefficients. These kind of problem are often called separable nonlinear least sqaures or varpro . There are formulas for calculating the errors of the coefficients and using the Jacobian. It is quite easy to do with python, if someone is interested i can share the code.

Our current fitting strategy is as follows:
1. For the ROI summed spectrum, we do non-linear fitting to figure out all the parameters.
2. For individual pixel fitting, we do linear-fitting only to calculate the peak intensity. Basically all the element peaks form a basis for linear fitting.

It will be highly appreciated if more fitting codes can be shared.

[TAC edited to off-set quote]

**Comment by ericdill** [comment]
@licode is this implemented in pyxrf already?

**Comment by licode** [comment]
yes. we implemented some algorithm already.
