### ISSUE TITLE
Line cut through mesh and fit

### ISSUE THREAD

**Issue by ericdill** [scikit-beam/scikit-beam#124]
Description
====

Obtain a cut through gridded images

Fit to lorentzian

Fit multiple lorentzians in 2-D with variable x and y widths

**Comment by ericdill** [comment]
@stuwilkins If I recall correctly this originally came from John Hill during a VisTrails demo **ages** ago.  Is this still something that you want an example notebook for?

**Comment by stuwilkins** [comment]
This isn’t something **I** want.

**Comment by ericdill** [comment]
Great!

**Comment by ericdill** [comment]
Thanks for the quick respnse :)
