### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by licode** [scikit-beam/scikit-beam#125]
Description
====

Configuration file is used to store the default data information for the program to run. For the fitting routine, the configuration file saves the default fitting parameters and some fitting recipes. We need to use a standard way to organize all the configuration files. 

Options
====
- [ ] JSON
- [ ] Dict
- [ ] yaml
- [ ] configfile

**Comment by ericdill** [comment]
We are using yaml files to do local configuration of metadatastore/filestore at each beamline.  I believe that @licode is using yaml files in https://github.com/NSLS-II-HXN/pyxrf

**Comment by ericdill** [comment]
Further work on this issue should be moved to pyxrf
