### ISSUE TITLE
Cake

### ISSUE THREAD

**Issue by ericdill** [scikit-beam/scikit-beam#17]
Description
====

Problems to be solved for this issue
====
 - [ ] XPD
 - [ ] CHX 

XPD
----
XPD needs to be able to select a "cake-slice" of a 2-D image relative to the image center (xc, yc) by specifying either:
 - [ ] r_min, r_max

or

 - [ ] r0, delta_r

and 

- [ ] theta_min, theta_max

or

- [ ] theta0, delta_theta

![xpd](https://cloud.githubusercontent.com/assets/6223243/3705680/e4dcebdc-1421-11e4-9ef1-0ce7d263b798.png)

**Output**
XPD's output should be a two 1-D numpy arrays. The x-axis should be the radius from the image center in terms of:
- [ ] pixels, if no additional information is provided
- [ ] two-theta, if the required information is provided (sample distance, wavelength)
- [ ] q, with the same required information as two-theta. 
- [ ] Q or 2-theta return value should be an input variable flag

The y-axis should be the average/sum/stdev/median/etc. of all pixels which share that x-value

CHX
----
CHX needs to be able to select a series of rings with ring centers (r0) and ring thicknesses (delta_r) relative to the image center (xc, yc)

![chx](https://cloud.githubusercontent.com/assets/6223243/3705681/e71bd606-1421-11e4-8642-53886b325c44.png)

**Output**
CHX's output should be one number for each ring.  This single number represents the sum or average of all pixels bounded by the rings

References
====
Image from http://oldwww.iucr.org/iucr-top/cif/cbf/PAPER/olivine.html

**Comment by danielballan** [comment]
Complaints Department: This issue has a misleadingly delicious title. :cake:

Leaving this here for @ericdill who is heroically closing old issues. Thanks!

**Comment by ericdill** [comment]
lol @danielballan . Thanks for the kudos :)
