### ISSUE TITLE
Issues about fitting summarized on Monday meeting 10/27/2014

### ISSUE THREAD

**Issue by licode** [scikit-beam/scikit-beam#184]
I listed some issues related to fitting within VisTrails framework. Those are not required to implement immediately, but can give us some hints in terms of user's respective.

- Set default parameter values for the fitting, thus users do not need to enter initial value each time. 
- Summarize fitting statistics in a good way.
- Fit a series of x,y data. For instance, fit multiple x,y data, and use previous fitting center as the initial center of next one.
- If users choose the constraint as free or fixed, then the range button should go away.
- Can we do summation on two or more functions using VisTrails framework? This can be done in lmfit part, but how about in the GUI level?
- What is the most convenient way for user to add a fitting function into VisTrials library? How many steps do they need to go?

**Comment by ericdill** [comment]
@licode is this still relevant?

**Comment by licode** [comment]
These functions are included in pyxrf.
