### ISSUE TITLE
Import error handling for scikit-image

### ISSUE THREAD

**Issue by ericdill** [scikit-beam/scikit-beam#212]

**Comment by danielballan** [comment]
@ericdill Would you elaborate?

**Comment by danielballan** [comment]
@ericdill bump

**Comment by ericdill** [comment]
I think this was in regards to isolating dependencies

**Comment by ericdill** [comment]
I.e., if you don't have scikit-image, degrade gracefully

**Comment by ericdill** [comment]
Yeah not entirely clear what this one was about and so it is not important
