### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by danielballan** [scikit-beam/scikit-beam#229]
Key Priority: Provide examples that answer a scientific question start to finish. Begin by pulling the data from DataBroker and finish with a publication-style plot.

## Where is the prior work on examples and demos?

- [ ] https://github.com/giltis/Demos/tree/seg_demo/demos (look in particular for shale segmentation)
- [ ] https://github.com/Nikea/scikit-xray/tree/master/examples
- [ ] Gabe is working surface area demo

Also see https://github.com/tacaswell/scikit-xray/tree/doc_update which may be a hot mess or may be a useful start.

## Setup and Installation Instructions

- [Set up a data broker](https://github.com/NSLS-II/metadataStore/wiki/Set-up-the-Data-Broker)
- [The internal wiki](https://github.com/Nikea/Internal/wiki) See especially demos, documents and presentations, etc.
- [House Conda Recipes](https://github.com/NSLS-II/conda-prescriptions)

## Strategy

Follow the general recipe for the [trackpy documentation](https://soft-matter.github.io/trackpy). For now, leave vistrails documentation up to vistrails devs.

## List of beamlines and their associated techniques that we will support

- IXS Inelastic X-ray Scattering
- XPD X-ray Powder Diffraction: 2D and 1D diffraction
- CHX Coherent Hard X-ray Scattering: 1- and 2-time correlation spectroscopy; GISAXS (Grazing Incidence Small-Angle X-ray Scattering)
- CSX Coherent Soft X-ray Scattering: 1- (and 2-time?) correlation spectroscopy; Reciprocal Space Mapping ("HKL scan")
- SRX Submicron Resolution X-ray Spectroscopy: fluorescence tomography and absorption tomography, either changing energy -- probing core electron levels, which 2D XANES (X-ray Absorption Near-edge Spectroscopy, pronounced "zanes") -- or rotating the sample between rasterized scans
- HXN Hard X-ray Nanoprobe: all of the above, simultaneously, on a nanometer-sized spot

See [Beamline Contacts](https://github.com/Nikea/Internal/wiki/Beamline-Contacts) for a rough idea of who is most knowledgable about the state of software support for each beamline.

[dill edit] Hard -> Soft in CSX, added E to XANS, Fixed beamline contacts description

**Comment by ericdill** [comment]
This issue is almost certainly done by the combination of getting try.nsls2.bnl.gov up and running, scikit-beam-examples being a growing collection of examples and #373
