### ISSUE TITLE
Find a tool for putting flowchats in notebooks (and thus sphinx docs)

### ISSUE THREAD

**Issue by danielballan** [scikit-beam/scikit-beam#233]
I think something like this came up at SciPy 2014, demonstrated in the context of circuit diagrams or something.

**Comment by tacaswell** [comment]
`pydot`  https://code.google.com/p/pydot/ is a thing.

**Comment by ericdill** [comment]
and here's an example of it being used in an ipython notebook

http://nbviewer.ipython.org/urls/courses.cit.cornell.edu/info6010/resources/assnt6.ipynb

**Comment by tacaswell** [comment]
There is also a sphinx extension in mpl to build class hierarchies which
uses pydot

**Comment by ericdill** [comment]
This seems useful in general, but not related to the scikit-beam project
