### ISSUE TITLE
Add numpy-to-VTK conversion and instructions for VTK-enabled 3D rendering 

### ISSUE THREAD

**Issue by giltis** [scikit-beam/scikit-beam#245]

**Comment by ericdill** [comment]
Are "instructions" a "demo"?

**Comment by danielballan** [comment]
> Yeah, pretty much

-- Gabe, just now

**Comment by danielballan** [comment]
As discussed recently: https://github.com/Kitware/VTK/blob/master/Wrapping/Python/vtk/util/numpy_support.py
