### ISSUE TITLE
Use PIMS to open ".edf" image files

### ISSUE THREAD

**Issue by sameera2004** [scikit-beam/scikit-beam#247]
We need to open ".edf" image file. (CHX? )

Fabio (https://github.com/kif/fabio) can open ".edf" file
---------
The general philosophy of the library is described in:
FabIO: easy access to two-dimensional X-ray detector images in Python
E. B. Knudsen, H. O. Sørensen, J. P. Wright, G. Goret and J. Kieffer
Journal of Applied Crystallography, Volume 46, Part 2, pages 537-539.
http://dx.doi.org/10.1107/S0021889813000150

**Comment by danielballan** [comment]
This can be done by subclassing `pims.ImageSequence` and overriding the `imread` method to use fabio.  Example over at NSLS-II-CHX: https://github.com/NSLS-II-CHX/chxtools/blob/new-pipeline/pyXPCS/pims_readers.py#L126

I will port this to pims or scikit-xray or both.

**Comment by ericdill** [comment]
Looks like we already have this at chxtools: https://github.com/NSLS-II-CHX/chxtools/pull/2. Thanks @danielballan

**Comment by CJ-Wright** [comment]
Can this still get ported? We'd like to use it too.
