### ISSUE TITLE
Current status on DataIO in vistrails

### ISSUE THREAD

**Issue by licode** [scikit-beam/scikit-beam#252]
What is the current status or plan on data IO with vistrails? For instance, how to get data from metadatastore or filestore and feed them into Vistrails for calculation? Do we need some wrapper functions, or just type command lines in PythonSource in VisTrails?

**Comment by ericdill** [comment]
It is unclear what the status of VisTrails is at NSLS2. There have not been many requests for this from management, as far as I can tell. Also, this should be moved to a different issue tracker. Perhaps NSLS-II/VTTools

**Comment by danielballan** [comment]
I have heard second-hand that upper management is receptive to our move
toward notebooks over VisTrails as a "portal" for users who want
approachable data analysts tools. We still support VisTrails, indirectly,
by providing a library of stateless functions that can be easily wrapped.

**Comment by heroux** [comment]
At some point, someone needs to justify why we don't consider Orange.

**Comment by danielballan** [comment]
Just to be clear to outsiders reading this, @heroux is referring to [this project](http://docs.orange.biolab.si/3/data-mining-library/). We are aware of it. There is no reason that anyone who is interested in the project couldn't integrate our analysis functions into it.
