### ISSUE TITLE
Single pixel fitting

### ISSUE THREAD

**Issue by licode** [scikit-beam/scikit-beam#253]
Sum spectrum fitting is done, next step is to do single pixel fitting for 2D map.

**Comment by licode** [comment]
Simple matrix method also needs to be added.

**Comment by licode** [comment]
And multi-threading to be considered. Use python multiprocessing.

**Comment by tacaswell** [comment]
I would suggest using `IPython.Parallel` instead.  They have already solved many of the hard dispatch/job management problems.

**Comment by licode** [comment]
Thanks, will check that.

**Comment by danielballan** [comment]
Status: Li has a branch, not yet pushed.

**Comment by ericdill** [comment]
closed by https://github.com/NSLS-II-HXN/PyXRF/pull/18
