### ISSUE TITLE
Image Corrections: Flat field correction

### ISSUE THREAD

**Issue by ericdill** [scikit-beam/scikit-beam#26]
Description
====
This is my best guess as to the requirements of flat field correction:

1. Expose the detector to as uniform of a field as possible (called the 'flat field')
1. Use the detector response to the uniform field as a correction, presumably by normalizing the flat field to 1 (removing the zero/negative pixels).
1. Divide the measured images by the normalized flat field images.

Open Questions about this Issue
====
1. Is the flat field something that is collected relatively infrequently and used for many experiments?
1. Presumably, anyone who is using a 2-D detector will require this functionality?

**Comment by danielballan** [comment]
Strategy: Put this image in the beamline config as a numpy array converted to a string.

    header = db[-1]
    images = pims.Images(header, 'lightfield_det', 'darkfield_det')
    correct_images = flat_field(images, header['beamline_config']['flatfield'])

If you have external or legacy data (not in broker):

    images = pims.ImageSequence('my/flash/drive/*.tiff')
    corrected_images = flat_field(images, my_flat_field_array)

If you don't know PIMS:

    images = np.load('my_image_stack.npy'

**Comment by ericdill** [comment]
This is out of scope for the scikit-beam project. It is also simply `light_field / flat_field`
