### ISSUE TITLE
Turn string constant into a list of strings

### ISSUE THREAD

**Issue by ericdill** [scikit-beam/scikit-beam#262]
It would make some sense to change this: `'non_fitting_values': {'element_list': 'Ar, Fe, Ce_L, Pt_M',` to be a list of strings instead of a single string in `skxray/fitting/base/parameter_data.py`

**Comment by souravsingh** [comment]
I would like to work on this

**Comment by ericdill** [comment]
Great!  Anything I/we can do to help you along?

**Comment by tacaswell** [comment]
Great, @licode can you please be responsible for reviewing this work?

**Comment by souravsingh** [comment]
I would like to know where do we find these string constants?

**Comment by tacaswell** [comment]
See https://github.com/tacaswell/scikit-beam/blob/master/skxray/core/fitting/base/parameter_data.py

**Comment by licode** [comment]
Sure. I can help on this.
