### ISSUE TITLE
Reciprocal space transform

### ISSUE THREAD

**Issue by licode** [scikit-beam/scikit-beam#286]
Need to double check ctrans.c and nsls2/recip.py on how to do the transform. There are some issues reported by hxn.

**Comment by sameera2004** [comment]
There is a seperate issues with HXN.  We(they?) have to figure out correct motors(order of the motors). The recip.py needs the setting_angles(six angles) , with ub matrix. 

I didn't touch the ctrans.c only took it from Stuart's pyspec. They used it for years, so I don't think we need to change it. What we need is, to have a separate helper function for recip.py(or modify) for HXN. 

 We (Me and @giltis) were planning to meet Wen(from HXN) to discuss this issue. Few times she came to meet us to convert her data to reciprocal space and see the 3D model. @giltis Did you get a chance to talk to her?

**Comment by licode** [comment]
Then we are talking about the same thing. This is the issue from Wen.

**Comment by ericdill** [comment]
Can you provide any more information about this issue?

**Comment by ericdill** [comment]
Closing as no additional information was provided. Please reopen with more information if this is still a problem
