### ISSUE TITLE
Real time plotting for CDI

### ISSUE THREAD

**Issue by licode** [scikit-beam/scikit-beam#288]

**Comment by tacaswell** [comment]
@licode You should put a bit more context in here so in 2 weeks when neither of us understand the conversation from the car this is still useful.

**Comment by licode** [comment]
Add call back function as an input to cdi_recon.  The call back function will be defined to do 1D or 2D plotting jobs.

**Comment by ericdill** [comment]
Is this callback supposed to be associated with bluesky?

**Comment by ericdill** [comment]
Or is this the CDI code that we already put into xray_vision: https://github.com/Nikea/xray-vision/blob/master/xray_vision/plotter.py?

**Comment by licode** [comment]
This is the one we put in xray-vision.

**Comment by ericdill** [comment]
Ah ok, can this be closed then?
