### ISSUE TITLE
Confusing function

### ISSUE THREAD

**Issue by ericdill** [scikit-beam/scikit-beam#301]
What is the purpose of this function? https://github.com/Nikea/scikit-xray/blob/master/skxray/core/roi.py#L431

It is intended to be used like this:
```python
mask_data1 = N_mask*duke_data[0:2000]
mask_data2 = N_mask*duke_data[2001: 3500]
mask_data3 = N_mask*duke_data[3501:5000]
image_sets = (mask_data1, mask_data2, mask_data3)
mean_int_sets, index_list = roi.mean_intensity_sets(image_sets, rings_mask)
combine_intensity = roi.combine_mean_intensity(mean_int_sets, index_list)
```

where index_list in the above code snippet is `[array([1, 2, 3, 4]), array([1, 2, 3, 4]), array([1, 2, 3, 4])]`.
and where:
```python
for means in mean_int_sets:
    print(means.shape)
```
produces
```
(2000, 4)
(1499, 4)
(1499, 4)
```
and 
```python
combine_intensity.shape
```
produces
```
(4998, 4)
```

Here is the problem...
----
Inside the function it checks to make sure that index_list is a list with a bunch of identical entries, then calls `np.vstack(mean_int_list)`.  Somewhat amusingly, if I pass in `index_list=['cat', 'cat', 'cat']`, then `combine_mean_intensity` still returns the same `combine_intensity` as the above code snipped.  

I guess I'm wondering if we can't just remove this function entirely, as it seems like a very very confusing wrapper around np.vstack.

[edit] i suck at spelling

**Comment by sameera2004** [comment]
@ericdill The purpose of this is in XSVS they collect data from different places of the same sample(capillary) 
100 images at point A
200 images at point B
150 images at point C , etc

Then they want to see whether the mean intensities

![screen shot 2015-07-24 at 11 15 43 am](https://cloud.githubusercontent.com/assets/5701652/8877790/5ca1d69a-31f5-11e5-9742-4a48265cb116.png)

Then they want to combine, in that case if it is not checking the index list properly we have to fix that issue and they need this combine_average one, If any of the image set gives very different mean intensities then they want to take that out and make the combine intensities

**Comment by ericdill** [comment]
So the `combine_mean_intensity` function is supposed to be able to remove an image set from the recombined intensities?

**Comment by sameera2004** [comment]
It doesn't need to
because they can view the mean_intensities for different images from the mean_intensity_plotter function and they can remove it from the list?
Or we can add into this function combine_mean_intensities?,

**Comment by ericdill** [comment]
I'm still not clear on what `combine_mean_intensity` is supposed to do.

**Comment by sameera2004** [comment]
It has to combine the mean intensities of each image_sets according to correct roi(index_list)
![screen shot 2015-07-24 at 11 51 17 am]
Mean intensities of the image sets
(https://cloud.githubusercontent.com/assets/5701652/8878688/7c45f454-31fa-11e5-88e7-81eda78bc7b8.png)

Combined images
![screen shot 2015-07-24 at 11 51 26 am](https://cloud.githubusercontent.com/assets/5701652/8878696/81ab8ada-31fa-11e5-99ed-d25436621ab6.png)

**Comment by ericdill** [comment]
What do you mean "correct roi"?

**Comment by sameera2004** [comment]
That is what index list gives, because we can't combine intensities from ROI 1 to ROI 2

**Comment by sameera2004** [comment]
In combine_mean_intensities it shows which ROI it represent ,

**Comment by sameera2004** [comment]
In mean_intenisty_plotter we plot different ROI's seperately

**Comment by ericdill** [comment]
After an offline conversation with @sameera2004 we came to the conclusion that this function will be useful once it accepts a list of data sets to drop. Closing issue, as it has been resolved.

**Comment by danielballan** [comment]
I'm still confused.

**Comment by ericdill** [comment]
Given no updates to this issue, declaring resolved
