### ISSUE TITLE
absorption effect for xrf fitting

### ISSUE THREAD

**Issue by licode** [scikit-beam/scikit-beam#330]
Needs to consider absorption effect from detector, or sample if possible.

**Comment by ericdill** [comment]
Is this already incorporated into pyxrf and https://github.com/scikit-beam/scikit-beam/blob/master/skxray/core/fitting/xrf_model.py?

**Comment by licode** [comment]
We can close this. Adjust branching ratio to solve this problem as a temporary solution.
