### ISSUE TITLE
Determining ideal bin size for Powder Diffraction

### ISSUE THREAD

**Issue by CJ-Wright** [scikit-beam/scikit-beam#34]
We will need a way to calculate the size of the bins for any integration algorithm we implement.  If the bins are too large, then we loose resolution in our diffraction pattern.  If the bins are too small, then some may contain no pixels, causing the pattern to become jagged.  This will also determine our maximum Q resolution, an important part of propagating diffraction pattern error.  Most likely this should be calculated from the detector setup/calibration information.

**Comment by ericdill** [comment]
This does not happen a priori, but the helper function was done in #55 .  "Automatically" determining bin sizes sounds like it requires a scientific publication to justify implementing an algorithm.  Please reopen if there is a scientific manuscript that we can obtain an algorithm from.
