### ISSUE TITLE
automate building the docs

### ISSUE THREAD

**Issue by ericdill** [scikit-beam/scikit-beam#372]
The docs should be automatically built on travis and pushed to github.

**Comment by danielballan** [comment]
I saw the subject and got excited that this was a PR, haha. I want to get this going on trackpy also. Might get to it soon.

**Comment by dgursoy** [comment]
how about using readthedocs?

**Comment by ericdill** [comment]
Duplicate of #96

**Comment by danielballan** [comment]
Do we want to try for a custom domain name, a la matplotlib.org? scikit-beam.org?

**Comment by dgursoy** [comment]
Doesn't hurt to have since the name is agreed upon. Though I wouldn't advertise before having sth solid at hand.

**Comment by ericdill** [comment]
Closed by #389
