### ISSUE TITLE
Partial computation examples

### ISSUE THREAD

**Issue by ericdill** [scikit-beam/scikit-beam#376]
Document some suggested design patterns for implementing partial computation.

- Using a class
- Using a generator (I'm not clear on how you would do this)

**Comment by danielballan** [comment]
a streaming pipeline via generators: https://github.com/scikit-beam/hackathon-2015-12/blob/master/demos/streaming_generator_demo.ipynb

**Comment by ericdill** [comment]
I am considering this complete. We have an example of algorithms operating on partial data implemented   for 

- [histogramming as a class] (https://github.com/scikit-beam/scikit-beam/blob/master/skbeam/core/accumulators/histogram.pyx#L33)
- [one-time correlation as a generator] (https://github.com/scikit-beam/scikit-beam/blob/master/skbeam/core/correlation.py#L201)
- [dpc as a generator (WIP)] (https://github.com/scikit-beam/scikit-beam/pull/392)
