### ISSUE TITLE
Switch to py.test

### ISSUE THREAD

**Issue by ericdill** [scikit-beam/scikit-beam#377]
It would be great if we could switch to py.test for our testing framework for a number of reasons.
1. It is very easy to use
2. It has a very large number of plugins
3. Errybody doin' it
4. ...and many others.

**Comment by tacaswell** [comment]
As part of this, known fail the tests that depend on lmfit or xraylib.

**Comment by tacaswell** [comment]
Also add a `test` function in the top namespace

**Comment by licode** [comment]
done.
