### ISSUE TITLE
Atomic Constants 

### ISSUE THREAD

**Issue by ericdill** [scikit-beam/scikit-beam#38]
Description
====

Need easy access to reasonably standard atomic constants (mass, etc...)

Need access to atomic constants that are specific to elastic scattering (scattering factors, Cromer-Mann coefficients, etc...), inelastic scattering (has some constants), X-ray fluorescence (also has some contants, etc...

Existing Options
====
Existing options may not solve the entire problem, but they serve as a starting point, either to beg/borrow/incorporate or simply as education on how someone else did this

 - [ ] [pyspec](https://github.com/stuwilkins/pyspec)
 - [x] [xraylib](https://github.com/tschoonj/xraylib)

Installation Procedures
====
To get `xraylib` set up 'the easy way'
----
from @tacaswell:

 - checkout my fork of conda-recipes and the xraylib branch (https://github.com/tacaswell/conda-recipes/tree/xraylib)

 - `conda build ~/other_source/conda-recipes/xraylib/`

(modify this to point at the actual location your system built)
 `conda install -c file:///home/tcaswell/miniconda/conda-bld/ xraylib`

At that point you should be able to `import xraylib` in python.

You will need `autoreconf` installed for this to work

**Comment by CJ-Wright** [comment]
Does anyone know what the Atomic Scattering function in xraylib units are?  Also, it returns a 3 element list but what are those values, and with which units?

**Comment by tacaswell** [comment]
https://github.com/tschoonj/xraylib/wiki/The-xraylib-API-list-of-all-functions#scattering-factors

**Comment by CJ-Wright** [comment]
Thank you!

**Comment by ericdill** [comment]
I'm pretty sure this was done when we added xraylib to scikit-xray
