### ISSUE TITLE
lineshapes question

### ISSUE THREAD

**Issue by ordirules** [scikit-beam/scikit-beam#381]
The lineshapes (core/fitting/lineshapes.py) seem like they could be very useful for multiple libraries in here in the long run. I would like to see that they are made as easy to use as possible.

I have a suggestion for perhaps standardizing future additions of lineshapes:
- convert all 1d functions to the format (x,pars) where pars is a dictionary object (see function below for example). This would allow fitting routines to easily use these functions without having to write their own wrapper functions.
- add a test to see if it's a Parameters object used by lmfit. It's a very useful library that allows bounding parameters during fitting and tweaking whether or not to fit them.

I've included an example below. Any suggestions about this or do you know of any nice python trickery to make this even neater? Anyway, I thought I'd give feedback. This might not be a good idea but I would like to hear others opinions.

```python 
def polyfitfunc(x,pars):
    ''' poly fit y = (sum_i) a_i*(x**b_i)
        (negative powers permitted, which is not longer polynomial)
        values should be named as follows:
            a0, ..., an
            b0, ..., bn
    '''

    # check if it's a Parameters object and grad the dictionary entries
    if(hasattr(pars['a0'],"value")):
        pars = pars.valuesdict()

    # check how many parameters there are
    cnt = 0
    while('a{}'.format(cnt) in pars):
        cnt += 1

    res = x*0

    # if none just return zeros
    if(cnt == -1):
        return res

    # now sum pars
    for i in range(cnt):
        res += pars['a{}'.format(i)]*x**(pars['b{}'.format(i)])

    return res
```

**Comment by ericdill** [comment]
Thanks for the input!  Help me understand what you mean by:

> This would allow fitting routines to easily use these functions without having to write their own wrapper functions.

Can you provide some short example code snippet that highlights the problem that you are trying to solve here? That would help me a lot!

**Comment by ordirules** [comment]
So I use my own fit object that fits using lmfit's minimize. Here is a snippet of the first few lines of the object followed by its use:

```python
from lmfit import minimize,Parameters
from scipy.optimize import leastsq

class FitObject:
    def __init__(self,fn=None,pars=None,logxy=[0,0]):
        '''Initialize the fit object. 
        fn - the fit function
        pars - the parameters
        '''
        self.fn = fn
        self.pars = pars
        self.mn = None
        self.oldpars = None
        self.logxy = logxy

    def residual(self,pars,xdata,ydata,erbs=None):
        '''The residual.'''
        if(erbs is not None):
            return (self.fn(xdata,pars)-ydata)/erbs
        else:
            return (self.fn(xdata,pars)-ydata)

    def fit(self,xdata,ydata,erbs=None):
        ''' Fit the function using the error bars.'''
        if(self.mn is not None):
            self.oldpars = self.mn.params
        if(erbs is None):
            self.mn = minimize(self.residual,self.pars,args=(xdata,ydata))
        else:
            self.mn = minimize(self.residual,self.pars,args=(xdata,ydata,erbs))
```

it's then called as (where mylib is my library):

```python
    from lmfit import Parameters
    from mylib.fit import FitObject
    pars = Parameters()
    for i in range(len(a)):
        pars.add('a{}'.format(i) , value=a[i], vary= True,min=minval)
        pars.add('b{}'.format(i) , value = b[i], vary= varyexps)

    fitfn = FitObject(fn=polyfitfunc,pars=pars)
    fitfn.fit(xdata,ydata)
```
 with polyfitfunc pasted above already. If polyfitfunc was something like:
```python
def polyfitfunc(x,constants, powers):

```
etc then I'd have to make a wrapper function:
```python
def newpolyfitfunc(x,pars):
```
that calls polyfitfunc and then pass that to my fit object. It's doable, but I believe standardizing fit functions could help make code cleaner. It's a small request but I think it would help.
Note that standardadizing does require one extra check since a Parameters object is not a dictionary (so you need to grab the dictionary from it first):
```python  
if(hasattr(pars['a0'],"value")):
    pars = pars.valuesdict()
```
but I think it makes things cleaner.

Pardon my verbosity but I am hoping that this will help rather than hinder things. If it still isn't clear, definitely let me know, I don't want this to waste your time :-)

**Comment by ericdill** [comment]
Have you looked at subclassing the `Model` object in lmfit?  It is designed to enable custom modeling functions and objects. Docs are http://lmfit.github.io/lmfit-py/model.html

And here is a notebook that I just threw together http://nbviewer.ipython.org/gist/ericdill/a4789f46a65ed4d89b45

**Comment by ordirules** [comment]
Oh wow that's perfect thanks!
This is a much nicer implementation. I didn't look at Model before, just assumed it required a lot of overhead given it is an object, but it grabs the args of the function intelligently. I have to get used to Python's powers (as opposed to the outdated [yorick]: http://yorick.sourceforge.net/)

Feel free to close this. I don't see this issue being relevant anymore :-)

**Comment by danielballan** [comment]
P.S. I wrote the original implementation of Model in grad school. It has
changed and become more complex since then but I can probably still answer
questions, so swing by if you have some.

**Comment by ordirules** [comment]
sure will do thanks! :-) It's very elegant by the way!

**Comment by ericdill** [comment]
Glad I could help. @danielballan is definitely the local expert in lmfit. I will let you close this issue if you feel that it is resolved

**Comment by ordirules** [comment]
yep closing :+1:
