### ISSUE TITLE
New forks are named scikit-xray

### ISSUE THREAD

**Issue by tjlane** [scikit-beam/scikit-beam#411]
Not sure if you guys have noticed this yet, but @chrisvam just made a new fork and the repo gets named "scikit-xray" by default.

https://github.com/chrisvam/scikit-xray

Beyond my git-foo to recommend a fix w/o doing some research.

**Comment by ericdill** [comment]
I am not seeing this same problem.  I just created the fork at [NSLS-II-CHX] (https://github.com/NSLS-II-CHX/scikit-beam) as soon as I saw this issue and it seems to be named scikit-beam.  @chrisvam can you delete and re-fork?

**Comment by ericdill** [comment]
Oh, Actually it looks like the fork from @chrisvam was created a while back.  The tip of his master branch is from December 2nd 2015 which is before the scikit-beam rename landed.  I would imagine that repo was also forked before the rename

**Comment by tjlane** [comment]
@ericdill aha! you are right. it seemed to let him "fork again", which was weird. Then GH had this little graphic which was even weirder:

<img width="224" alt="screen shot 2016-02-09 at 2 37 21 pm" src="https://cloud.githubusercontent.com/assets/2085719/12933079/1bc6280e-cf3b-11e5-9a88-5d33d39164ad.png">


But if you delete and start over, all seems well.

**Comment by ericdill** [comment]
Ah, good. I'm glad it was that simple.  I was nervous that it was going to be way more complicated than that!

**Comment by tjlane** [comment]
lol makes two of us
