### ISSUE TITLE
Compile ctrans extension on Windows.

### ISSUE THREAD

**Issue by ericdill** [scikit-beam/scikit-beam#418]
The ctrans extension is not currently compiling on Windows.  The build log can be seen [here](https://gist.github.com/ericdill/bdc86eb81e338ca4624b).  I am disabling building it on windows for now and adding some warning machinery into the places where it is imported in the code base in #417 . Leaving this issue here so I can point to it in the code base.

**Comment by stuwilkins** [comment]
Hi @ericdill Do you have a place this is building to test. I am working on changes to make this use openmp. I can incorporate some changes there as it looks like it is mostly header file problems.

**Comment by ericdill** [comment]
Hi @stuwilkins , Thanks for offering to try and get this running!

I am building the 'build-for-windows' branch on my fork of scikit-beam with [this] repository (https://github.com/scikit-beam/skbeam-recipes).  It has hooks into appveyor to build for windows, travis-ci to build for osx and circle-ci to build for linux.  

I'm still working out some kinks in the automated windows builds.  It is sort of fussy to set all of this up so I'm happy to help if you wanted to set up this automated building on a fork of scikit-beam/skbeam-recipes so you can control which branch it builds and restart the builds when you update that branch.  I'll be at the lab next week, T-Th, so I can also help you set this up in person if you want.

**Comment by licode** [comment]
I suggest we always put ifdef header for pthread, openmp and even GPU later. So it is easy to handle system dependency problem later. I think windows/mac will handle openmp/GPU a bit differently from linux.

**Comment by stuwilkins** [comment]
I think we should be ok with OpenMP. As it uses compiler pragmas this is much easier to turn on and off (ignore) at compilation. The rest just looks like the usual crud because Windows never adheres to any standards. Adding compiler directives is a good idea.

**Comment by licode** [comment]
no worry on windows for now.
