### ISSUE TITLE
deploy to pypi too

### ISSUE THREAD

**Issue by ericdill** [scikit-beam/scikit-beam#421]
It would be great to deploy our tags to pypi. I bet that I can use the skbeam-recipes repo to automatically do this for linux/win/osx

**Comment by ericdill** [comment]
Deploy to pypi from appveyor when new tags are pushed: https://www.appveyor.com/docs/deployment#deploy-on-tag-github-and-gitlab-only (Obviously requires a working appveyor first...)

**Comment by ericdill** [comment]
deploy to pypi from travis when new tags are pushed: https://docs.travis-ci.com/user/deployment/pypi

**Comment by tacaswell** [comment]
https://pypi.org/project/scikit-beam/ <- done
