### ISSUE TITLE
Register 1-D curves: Fit, Scale & Shift

### ISSUE THREAD

**Issue by ericdill** [scikit-beam/scikit-beam#44]
Description
====
The Inelastic scattering beamline at NSLS-II, IXS (10-ID), has 6 strip detectors which nominally should produce the same datasets.  However, due to measurement error, detector issues, crystal issues, etc., these six curves might not be identical.  Given that the elastic scattering peak should be identical for each of the six measured curves, the elastic peak can be fit and used as a handle with which to scale and shift all curves.  The elastic peak should be centered on the zero of the x-axis, since the elastic peak, by definition, has an energy transfer of 0 (ΔE=0).  It is unclear how the width of the elastic peak should be determined.

Problems to be solved
====
 - [ ] Determine elastic peak function that should be used to fit the elastic peak
 - [ ] Fit elastic peak
 - [ ] Shift peaks to be centered at ΔE=0
 - [ ] Determine how to scale peaks to the appropriate width
 - [ ] Scale peaks to the appropriate width

**Comment by licode** [comment]
I think this is done, @ericdill ?

**Comment by ericdill** [comment]
Yeah it is being done in https://github.com/nsls-ii-ixs/ixstools
