### ISSUE TITLE
Automated builds with conda-forge

### ISSUE THREAD

**Issue by ericdill** [scikit-beam/scikit-beam#443]
I am in the process of adding scikit-beam to conda-forge. This will allow users to easily install this *on any platform* with conda (conda install -c conda-forge scikit-beam). The maintenance burden here is light as all testing and releases are built and deployed automatically with CI. Changes to how it is being built can be controlled by changing the recipe in https://github.com/conda-forge/scikit-beam-feedstock (once conda-forge/staged-recipes#595 is merged). If you have any interest in being added as a maintainer (to make new releases for instance), post here and I can happily add you to the maintainers list now or at some point in the future. Thanks!

**Comment by licode** [comment]
👍  on conda-forge for multiple platforms. Please add me as a maintainer. thanks!

**Comment by ericdill** [comment]
(Finally) done in https://github.com/conda-forge/staged-recipes/pull/595
