### ISSUE TITLE
arbitrary bins for binned_statistic

### ISSUE THREAD

**Issue by jrmlhermitte** [scikit-beam/scikit-beam#471]
I am thinking, it would be nice to allow for more arbitrary bins for `core.accumulators.binned_statistic`.
What I used to do with my own code was treat bin_edges differently. Each bin had a pair of edges, let's call it `bin_list`.
Say, to bin numbers 1 through 6, `bin_edges` vs `bin_list` would be:

``` python
bin_edges = [1,2,3,4,5,6]
bin_list = [1,2, 2,3, 3,4, 4,5, 5,6]
```

The latter case is more powerful as it allows for gaps between bins, to skip every other bin, for instance:

``` python
bin_list = [1,2, 3,4, 5,6]
```

whereas for `bin_edges`, you'd have to count every bin and skip every other bin.

It would break the current API to change `BinnedStatistic` to allow for arbitrary edges, so I propose a prototype function:

``` python
binmask, bin_edges = bin_list_to_mask_edges(binids, bin_edges)
```

which would basically create a mask that masks out pixels and adjusts `bin_edges` to mimic this effect.

So I'm basically asking, does something like a `bin_list` sound useful? If yes, would there be some way of incorporating it into BinnedStatistic, or as an alternative, does a function like bin_list_to_mask_edges sound useful for scikit-beam?
(I am writing this with the intention that eventually BinnedStatistic might be sped up for strongly masked regions, maybe in the future...)

I just wondered if anyone had other interesting ideas? Am I perhaps over thinking this? thanks!
@chrisvam @tacaswell @danielballan

**Comment by chrisvam** [comment]
Hi Julien,

My thoughts: that sounds an advanced feature that would be useful for some people.  However, if I understand correctly, the same effect can be achieved with the current interface, specifying bin edges and ignoring results for bins that one doesn't care about (although perhaps with a performance penalty compared to what you are thinking about).  My best guess is that we should focus on fleshing out scikit-beam with more basic functionality and not focus on advanced stuff too much yet.  One example:  I would next like to work on getting a two-threshold fast peak-finder in.  Just my opinion.  Others may disagree.

**Comment by ordirules** [comment]
I thought about it more and I agree. This feature can be added with a simple wrapper function (selecting even numbered bins, only issue might be worrying about not making the edges overlap), and as you say, adding more features may be a better idea than speeding up/complicating existing ones.

Thanks for the input.

**Comment by tacaswell** [comment]
For images, the general case is to fall back to taking label images (integer arrays with 0 for 'background' and positive integers for ROIs) which allow the user to construct _any_ sort of binning they want (which is what the functions in the `roi` module provide tools to make).

The most general way to do this is to have function that take in a `hash` function which maps for the 'binning domain' (what is the correct term for this) to labels.

**Comment by ordirules** [comment]
I forgot about the roi code but that is a good idea. BinnedStatistic should maybe use these routines as well (for the case of 1D Radial gridding use `rings`), and maybe make a new one for r phi wedges. This would increase the connectivity/visibility of routines.

**Comment by jrmlhermitte** [comment]
I think this is too specific and more cognitive overhead than anything. Closing.
