### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by ericdill** [scikit-beam/scikit-beam#472]
It's nearing time to cut a new release of scikit-beam. Lots of new features have been added recently. Anything else that people want to get in before we cut a release?

**Comment by licode** [comment]
sounds good to me.

**Comment by sameera2004** [comment]
Fine with me

**Comment by CJ-Wright** [comment]
I would like a new release.

**Comment by ericdill** [comment]
Thanks for the tag @danielballan!  In the future, could you also update [whats_new] (https://github.com/scikit-beam/scikit-beam/blob/master/doc/whats_new.rst) when you tag?

**Comment by danielballan** [comment]
Oops. Yes. I'll go back and do that retroactively. The docs have larger issues which we are in the process of fixing.

**Comment by ericdill** [comment]
> Oops. Yes. I'll go back and do that retroactively

Awesome, thanks :grinning: 

> The docs have larger issues which we are in the process of fixing.

yikes.. thanks for tackling that :grimacing:

**Comment by ericdill** [comment]
conda-forge release is in progress: https://github.com/conda-forge/scikit-beam-feedstock/pull/1

will circle back and update once that PR is functional

**Comment by ericdill** [comment]
I expect this will take a day or two due to the lengthy iteration cycle (conda-forge queues are quite long)

**Comment by ericdill** [comment]
Fingers crossed this will make windows binaries now too

**Comment by ericdill** [comment]
Update: Merged in the PR that added windows support and.... github changed the sha of the archive underneath me. Once this builds: https://github.com/conda-forge/scikit-beam-feedstock/pull/3 we will be close to 0.0.9 binaries being available (just need to merge it in after all the green checkmarks appear)

**Comment by licode** [comment]
Just merged. Thanks for the update!

**Comment by licode** [comment]
0.0.9 is ready. closed.

**Comment by ericdill** [comment]
This issue is serving as a thing that reminds me to check in on conda-forge/scikit-beam-feedstock.  Do you mind if we leave it open until 0.0.9 is available on anaconda.org/conda-forge?

**Comment by licode** [comment]
sounds reasonable.
