### ISSUE TITLE
sort out relative vs absolute imports

### ISSUE THREAD

**Issue by tacaswell** [scikit-beam/scikit-beam#49]
determine if best practice is to use 

```
from nsls2.foo import bar
```

or 

```
from .foo import bar
```

**Comment by ericdill** [comment]
Seems that we want to standardize on the following code snippet for library code

```python
from __future__ import absolute_import

from .foo import bar
```

and probably the following code for tests so that the tests could be used to test scikit-beam when it is installed with python setup.py install and conda install scikit-beam

```python
from skbeam.foo import bar
```

**Comment by ericdill** [comment]
@tacaswell did you integrate this anywhere into your massive docs upgrade?

**Comment by tacaswell** [comment]
Yes

**Comment by ericdill** [comment]
Ok,  great.  Thanks
