### ISSUE TITLE
CI: drop python 3.4 CI support

### ISSUE THREAD

**Issue by CJ-Wright** [scikit-beam/scikit-beam#501]
Can we drop python 3.4 Travis support?

**Comment by licode** [comment]
sounds reasonable to me.

**Comment by licode** [comment]
thanks for updating this in your pr.

**Comment by CJ-Wright** [comment]
Sure, I've also moved numpy to 11 and 12

**Comment by danielballan** [comment]
Just to clarify for myself (and more importantly anyone else reading along), we're talking about dropping the 3.4 Travis test to save on testing time but maintaining support for all Python versions >= 2.7, correct?

**Comment by stuartcampbell** [comment]
Can I just ask why we need to drop support for 3.4 ? I'm not saying that we shouldn't, just a want to understand the rational. 

Yes, I think we should maintain 2.7

**Comment by ericdill** [comment]
FWIW conda-forge does not build python 3.4 packages any longer. Since conda-forge isn't building for 3.4 it is going to be increasingly difficult to create a "modern" python 3.4 environment with the latest versions of the packages needed to create the test environment

**Comment by danielballan** [comment]
That's for the useful point of information, @ericdill. I assume that older versions of numpy and so on will still be available? So I can't test latest numpy + Python 3.4, but I can still test old numpy + Python 3.4? That seems like a realistic scenario worth testing, provided we are willing to wait for the builds to finish.

**Comment by ericdill** [comment]
@danielballan Yes that's correct. conda-forge is not going to remove python 3.4 builds from the conda-forge channel, so you'll still be able to build a python 3.4 environment to test against. To release a python 3.4 build with conda-forge you'll need to muck with the CI service files on the scikit-beam feedstock to make sure the python 3.4 binaries do get built. That might be a sticking point, but I can help sort that out when the next release rolls around

**Comment by stuartcampbell** [comment]
Thanks for the info @ericdill

**Comment by CJ-Wright** [comment]
I guess if we are not testing it on Travis I don't really consider it supported, if it works then that is a happy accident. I guess my point was mostly that conda-forge has moved beyond python34 (and numpy10) and we might consider doing the same.

**Comment by CJ-Wright** [comment]
On a related note, this is why #510 is failing, we can't install python3.6 and numpy1.10 together and get all the libraries we need, see: https://travis-ci.org/scikit-beam/scikit-beam/jobs/253441062#L269

**Comment by ericdill** [comment]
If the rationale behind dropping 3.4 support is that conda-forge is no longer building python 3.4 then we should also stop linking against numpy 1.10/1.11 since conda-forge only packages the latest two versions of numpy

**Comment by tacaswell** [comment]
I am also :+1: on dropping 3.4.

**Comment by mrakitin** [comment]
We now build on Python 3.6 and 3.7 (updated via https://github.com/scikit-beam/scikit-beam/pull/552). Closing as outdated & resolved.
