### ISSUE TITLE
Hot fix release

### ISSUE THREAD

**Issue by CJ-Wright** [scikit-beam/scikit-beam#509]
Our most recent release contains some python 2 incompatibilities
https://github.com/scikit-beam/scikit-beam/blob/v0.0.11/skbeam/core/correlation.py#L1164

Can we put out another release? (it is breaking our conda-forge release)

**Comment by licode** [comment]
I am aware of that. py2 issue is already fixed in current master. I am reviewing one PR now. I plan to add a new release after merging that new PR. It should be done tomorrow or early next week.

**Comment by licode** [comment]
Any idea to quickly fix this for new release? https://github.com/scikit-beam/scikit-beam/pull/502

**Comment by CJ-Wright** [comment]
I can try to get that in by COB today.

**Comment by mrakitin** [comment]
Closing as outdated.
