### ISSUE TITLE
bug in lazy_one_time

### ISSUE THREAD

**Issue by mpmdean** [scikit-beam/scikit-beam#512]
Hi @sameera2004 

When using the srv1 current kernal on jupyterhub calling
g2s, lag_steps = corr.multi_tau_auto_corr(num_levels, num_bufs, labeled_roi_array, (im for im in stack_clean))
 produces the error below

Line 199 in skbeam/core/correlation.py
Needs // rather than / in order to return a int and not a float. 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-c78a1cf24ed9> in <module>()
      2 num_bufs = 12
      3 
----> 4 g2s, lag_steps = corr.multi_tau_auto_corr(num_levels, num_bufs, labeled_roi_array, (im for im in stack_clean))
      5 # lag_staps are delays for multiple tau analysis
      6 lag_time = image_time / 60 # minutes

/opt/conda_envs/analysis-17Q2.0/lib/python3.6/site-packages/skbeam/core/correlation.py in multi_tau_auto_corr(num_levels, num_bufs, labels, images)
    370     """
    371     gen = lazy_one_time(images, num_levels, num_bufs, labels)
--> 372     for result in gen:
    373         pass
    374     return result.g2, result.lag_steps

/opt/conda_envs/analysis-17Q2.0/lib/python3.6/site-packages/skbeam/core/correlation.py in lazy_one_time(image_iterable, num_levels, num_bufs, labels, internal_state)
    286 
    287     if internal_state is None:
--> 288         internal_state = _init_state_one_time(num_levels, num_bufs, labels)
    289     # create a shorthand reference to the results and state named tuple
    290     s = internal_state

/opt/conda_envs/analysis-17Q2.0/lib/python3.6/site-packages/skbeam/core/correlation.py in _init_state_one_time(num_levels, num_bufs, labels)
    197     # accumulate computations into G as the algorithm proceeds.
    198     G = np.zeros(((num_levels + 1) * num_bufs / 2, num_rois),
--> 199                  dtype=np.float64)
    200     # matrix for normalizing G into g2
    201     past_intensity = np.zeros_like(G)

TypeError: 'float' object cannot be interpreted as an integer

**Comment by licode** [comment]
I think this issue should be fixed at new version 0.0.12. We will do update at beamline during beam shutdown time.
