### ISSUE TITLE
Math is not rendering properly in the docs

### ISSUE THREAD

**Issue by ericdill** [scikit-beam/scikit-beam#516]
Content in the docstrings like

```python
def q_to_twotheta(q, wavelength):
    r"""
    Helper function to convert q to two-theta.
    By definition the relationship is:
    ..math ::
        \sin\left(\frac{2\theta}{2}\right) = \frac{\lambda q}{4 \pi}
    thus
    ..math ::
        2\theta_n = 2 \arcsin\left(\frac{\lambda q}{4 \pi}\right
    Parameters
    ----------
    q : array
        An array of :math:`q` values
    wavelength : float
        Wavelength of the incoming x-rays
    Returns
    -------
    two_theta : array
        An array of :math:`2\theta` values
    """
    q = np.asarray(q)
    wavelength = float(wavelength)
    pre_factor = wavelength / (4 * np.pi)
    return 2 * np.arcsin(q * pre_factor)
```
in ``skbeam/core/utils.py`` is not rendering properly in the documentation at scikit-beam.github.io/scikit-beam [here](https://scikit-beam.github.io/scikit-beam/resource/api/core/utils.html#skbeam.core.utils.q_to_twotheta)

screenshot: 
<img width="736" alt="screen shot 2017-09-01 at 8 37 15 pm" src="https://user-images.githubusercontent.com/6223243/29991475-91d8b044-8f55-11e7-98b9-26070d0ba6f4.png">

I have no idea what magic is needed to make this work. Taking a stab in the dark and hoping that @danielballan will have some documentation juju to fix this

**Comment by tacaswell** [comment]
I suspect it is missing blank line both above `.. math` and  below the body.

**Comment by ordirules** [comment]
tried it out and it seems that you also have it slightly wrong based on sphinx [documentation](http://www.sphinx-doc.org/en/stable/ext/math.html)
should be `.. math::` and not `..math ::` (you also need that new line as well though).
added PR in #520
