### ISSUE TITLE
Cythonize binned statistic?

### ISSUE THREAD

**Issue by CJ-Wright** [scikit-beam/scikit-beam#519]
Would it be possible to Cythonize `binned_statisticDD` and children? Would this speed things up?

**Comment by danielballan** [comment]
My sense (without checking the code again) is that it's already well vectorized. Cython is most useful for eliminating "hot loops" that can't be vectorized by using existing functionality in numpy, scipy, or other compiled code. If you are interested in trying this, I would start by benchmarking the code and identifying whether it spends a significant amount of time in Python loops.

**Comment by danielballan** [comment]
I should mention, good tools for this include line_profiler and RunSnakeRun.

**Comment by ericdill** [comment]
upvote for using a line profiler. I have had good results using `line_profiler`. No experience with RunSnakeRun.

**Comment by ordirules** [comment]
you could try, the histogram is a good example of cythonization.
I'd be interested to see what the timing results are, but would agree with @danielballan . It looks vectorized. But you never know until you try!

**Comment by CJ-Wright** [comment]
For all the statistics but a few there is a giant for loop which:
1. pulls from the array all the data in that bin
1. maps a function onto that array

I don't think that loop is vectorized, right?

**Comment by ericdill** [comment]
@CJ-Wright  -- no longer of interest?

**Comment by CJ-Wright** [comment]
Yea the [PR I put in](https://github.com/scikit-beam/scikit-beam/pull/500#discussion_r145748107) got a 10x speedup which is good enough for me (currently). I tried a bunch of numba stuff, but it didn't make it much faster (or at all).
