### ISSUE TITLE
2D SavitzkyGolay smoothing algorithm 

### ISSUE THREAD

**Issue by mpmdean** [scikit-beam/scikit-beam#531]
In the context of XPCS and other speckle techniques, the 2D SavitzkyGolay smoothing algorithm is very useful. 

Would you consider incorporating this into scikit-beam?

An implementation is described here:
http://scipy-cookbook.readthedocs.io/items/SavitzkyGolay.html

As far as I'm aware scipy (and other packages) only provide an implementation in 1D.

**Comment by danielballan** [comment]
Yes. I wonder why this isn't included in scipy proper. In any case, I think this would be a good addition to scikit-beam.

Do you have the bandwidth to submit at PR copy/pasting this example, @mpmdean? Perhaps a new module in the [skbeam.core](https://github.com/scikit-beam/scikit-beam/tree/master/skbeam/core) package, something like `skbeam.core.smoothing`, would be suitable.

**Comment by ericdill** [comment]
👍 from me too. I've got a special place in my heart for 2D savitzky-golay filtering. Most of my grad work was based around finding diffraction spots using a 2-D savgol filter. @mpmdean happy to help out if you need it.

**Comment by mpmdean** [comment]
I have a new scikit-beam branch locally (add_2D_sg) but am having trouble pushing it back to github.

`(test_scikit-beam) 10-4-12-246:scikit-beam markdean$  git push origin add_2D_sg
remote: Permission to scikit-beam/scikit-beam.git denied to mpmdean.
fatal: unable to access 'https://github.com/scikit-beam/scikit-beam.git/': The requested URL returned error: 403
(test_scikit-beam) 10-4-12-246:scikit-beam markdean$ `

I have very little experience with git, so likely I'm doing something stupid. Either that or I have a git config problem.  @ericdill can you help?

**Comment by jrmlhermitte** [comment]
I would be tempted to ask scipy to push it upstream.

One small issue we need to worry about is licenses. Looks like it's compatible with our license (https://github.com/scipy/scipy/blob/master/LICENSE.txt), but it may be worth reading more carefully.

(And yes, I'm surprised it hasn't been pushed upstream anywhere. Love this algorithm :) )
