### ISSUE TITLE
1-time from 2-time does not average appropriately

### ISSUE THREAD

**Issue by ambarb** [scikit-beam/scikit-beam#565]
https://github.com/scikit-beam/scikit-beam/blob/4fc0cfd4c20292e481a30e233cc70d27a3e5b5e0/skbeam/core/correlation.py#L829-L851

The 1-time results is the average of the 2-time array along the diagonal.  This function calculates the sum and divides by the total number of frames.  But the total number of "equivalent" pixels are not equal to the total number of frames (say the t1=0, t2= final_frame is one pixel).

Should be a simple fix to https://github.com/scikit-beam/scikit-beam/blob/4fc0cfd4c20292e481a30e233cc70d27a3e5b5e0/skbeam/core/correlation.py#L850

None elegantly:
`one_time_corr[:, j] = np.trace(g, offset=j)/ (two_time_corr.shape[2] - j )`
should fix it.

Confirmed plots in notebook, but I haven't cloned this repo to make the changes. But pictures of the "current sk-beam code" versus the change above (aka "fair averaging") are below.

![Toy_example](https://user-images.githubusercontent.com/13630233/80168745-a6101980-85b1-11ea-8743-3d23db095a34.png)
![Real_data](https://user-images.githubusercontent.com/13630233/80168750-a90b0a00-85b1-11ea-903e-90a0cc95d14a.png)

**Comment by ambarb** [comment]
If the proposed change looks ok,   I will have time next week.  It is a small change and I could use the practice.

**Comment by dmgav** [comment]
It looks like the change is fixing the problem.

**Comment by ambarb** [comment]
ok.  I found something else and will do a PR on both sometime next week.

**Comment by ambarb** [comment]
does anyone have suggestions on improving test for this function? 
https://github.com/scikit-beam/scikit-beam/blob/4fc0cfd4c20292e481a30e233cc70d27a3e5b5e0/skbeam/core/tests/test_correlation.py#L205-L224 

I have to change it as the test failed with definition changes.  It also doesn't test if two arrays are handled correctly so I had planned on adding this too.

**Comment by ambarb** [comment]
https://github.com/scikit-beam/scikit-beam/pull/566
