### ISSUE TITLE
Pool of physics functions

### ISSUE THREAD

**Issue by licode** [scikit-beam/scikit-beam#57]
It is convenient if we can collect more physics functions for fitting. This will speed up our work to cover more beamlines. 

I wrote some functions for fluorescence fitting, as shown in https://github.com/licode/NSLS2/blob/xrf_fit/nsls2/fitting/model/physics_peak.py (PR #40)

Also some can be found in lmfit
https://github.com/licode/lmfit-py/blob/master/lmfit/utilfuncs.py

To be done:
- [ ] collect functions or models from beamline scientists or other resources
- [ ] modularize all the physics functions in an efficient way

[TAC edited to add githubfoo]

**Comment by ericdill** [comment]
This is done. If we want some more physics functions, then we should specify exactly which function in an issue or just put in a PR with the desired function.  This catchall issue will never be closed otherwise
