### ISSUE TITLE
looks like the documentation webpage is down. 

### ISSUE THREAD

**Issue by ambarb** [scikit-beam/scikit-beam#573]
https://scikit-beam.github.io

**Comment by ambarb** [comment]
So it looks like the old page is still discoverable by google search.  Can we set up a re-direct?

http://scikit-beam.github.io/scikit-beam/

**Comment by mrakitin** [comment]
Done via creating this file in the new repo: https://github.com/scikit-beam/scikit-beam.github.io/blob/main/index.html (thanks to @danielballan for previous examples).

https://scikit-beam.github.io now redirects to https://scikit-beam.github.io/scikit-beam/.

**Comment by ambarb** [comment]
Thanks @mrakitin
