### ISSUE TITLE
Use PIMS for image series/stack file I/O

### ISSUE THREAD

**Issue by tacaswell** [scikit-beam/scikit-beam#58]
Description
-----
We will need to read in multi-image sequences from disk.  Instead of doing this ad-hoc, extend PIMS (https://github.com/soft-matter/pims) which already has code to provide a uniform interface to different file-format backends

There are already several implementations of tiff readers as well as png, jpeg, etc

There is a prototype of a sensible dispatch function as well (https://github.com/soft-matter/pims/pull/74)

getting proper docs is on the TODO list over there (https://github.com/soft-matter/pims/issues/26)

To add a new file type you just need to sub-class `pims.FramesSequence` and override 3 functions and 2 properties.  You then get lazy loading + numpy style slicing.

Problems to Solve
------

These can either be done in our code base or pushed back up to PIMS

 - [ ] determine if fabio deals with any file formats PIMS can't already do, and if so wrap for PIMS (should go to PIMS)
 - [ ] if avizo can be multi-frame, wrap with PIMS (should probably go to PIMS)
 - [ ] wrap pySpec with PIMS (should probably stay here)

**Comment by ericdill** [comment]
@danielballan @tacaswell This is almost certainly already done.  Reopen if it is not
