### ISSUE TITLE
Integration with lmfit

### ISSUE THREAD

**Issue by licode** [scikit-beam/scikit-beam#94]
Description
====
An interface needs to be designed to integrate cost function and xrf fitting parameters into lmfit framework. We have multiple cost functions to deal with, and the data structure for xrf fitting parameters is complicated.

**Comment by danielballan** [comment]
@licode How about now?

**Comment by licode** [comment]
That was the original idea. Having developed the fluorescence fitting model, I find that this example is too specific and domain knowledge related, not like general gaussian or exponential functions. xrf_model itself takes more than 1K lines. So I suggest the better place to put the code is in scikit-xray.

**Comment by ericdill** [comment]
This is almost certainly done
